config/routes.rb
Rails.application.routes.draw do
  root 'application#home'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy', as: 'signout'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')

  resources :users do
    resources :funds
    resources :investments
  end

  get '/funds/top_funds' => 'funds#top_funds', as: 'top_funds'
  get '/investments/latest_investments' => 'investments#latest', as: 'latest'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :fund
  belongs_to :user

  validates :symbol, presence: true
end

app/models/fund.rb
class Fund < ApplicationRecord
  has_many :investments
  has_many :users, through: :investments

  validates :symbol, presence: true, uniqueness: true
  validates_format_of :symbol, :with => /[A-Za-z]*/

  scope :top_funds, -> { joins(:users).group(:fund_id).having("count(user_id) > 1") }
end

app/models/investment.rb
class Investment < ApplicationRecord
  belongs_to :fund
  belongs_to :user

  validates :quantity, presence: true, numericality: {greater_than: 0}
  validates :price, presence: true, numericality: {greater_than: 0}
  validates :fund, :associated => true, :presence => true

  scope :latest, -> { order(created_at: :desc).limit(5)}

  def new_fund=(new_fund)
    if !new_fund[:symbol].empty?
      fund = Fund.find_or_create_by(new_fund)
      self.fund = fund
    end
  end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  belongs_to :fund, inverse_of: :funds
  belongs_to :user

  validates :name, presence: true
  validates :strategy, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :investments
  has_many :funds, through: :investments

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :password, presence: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :sign_in?

  def home
  end

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def sign_in?
    !!current_user
  end

  def require_signin
    redirect_to '/signin' unless sign_in?
  end
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController
  before_action :require_signin
  skip_before_action :require_signin, only: [:index]

  def index
    @funds = Fund.all
  end

  def top_funds
    @top_funds = Fund.top_funds
  end

  private

  def fund_params
    params.require(:fund).permit(:symbol, :search)
  end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  before_action :require_signin

  def index
    @investments = Investment.all
  end

  def new
    @user = User.find(params[:user_id])
    @investment = @user.investments.build
  end

  def create
    @user = User.find(params[:user_id])
    @investment = @user.investments.build(investment_params)
    if @investment.save
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def destroy
    @investment = Investment.find_by(id: params[:id])
    @investment.destroy
    redirect_to user_path(current_user)
  end

  def latest
    @latest_investments = Investment.latest
  end

  private

  def investment_params
    params.require(:investment).permit(:quantity, :price, :user_id, :fund_id,
      new_fund: [:symbol])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if auth_hash
      @user = User.find_or_create_by(uid: auth_hash['uid'][0..8]) do |u|
        u.id = auth_hash['uid'][0..8]
        u.username = unique_username
        u.name = auth_hash['info']['name']
        u.email = auth_hash['info']['email']
        u.password = SecureRandom.hex
      end
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      @user = User.find_by(username: params[:username])
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user.id)
      else
        flash[:notice] = "Invalid username or password. Please try again."
        redirect_to signin_path
      end
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  private

  def unique_username
    auth_hash['info']['email'].split("@").first + rand(1...100).to_s
  end

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :verify_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def verify_user
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to signin_url, notice: "You are not authorized to access this account."
    end
  end

  def user_params
    params.require(:user).permit(:username, :password, :email, :uid, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/funds_helper.rb
module FundsHelper
  def has_investments(fund)
    if fund.investments.count > 0
      true
    end
  end
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.html.erb
<div class="center-screen">
  <h1 id="title">Welcome to i.nvest!</h1>
  <h3>Create and share your i.nvestments.</h3>
  <br>
  <p>Sign up or sign in below to get started:</p>
    <%= button_to "Sign Up", new_user_path, method: :get, :class => "home-button" %>
    <br>
    <%= button_to "Sign In", signin_path, method: :get, :class => "home-button" %>
</div>

app/views/funds/index.html.erb
<div class="center-horizontal block">
  <h1>All Funds</h1>

  <ul>
  <% @funds.each do |fund| %>
    <li><%= fund.symbol %></li>
    <% end %>
  </ul>
  <br><br>
</div>

app/views/funds/top_funds.html.erb
<div class="center-horizontal block">
  <h1>Most Popular Funds</h1>

  <ul>
  <% @top_funds.each do |fund| %>
    <li><%= fund.symbol %></li>
    <% end %>
  </ul>
  <br><br>
</div>

app/views/investments/_form.html.erb
<% if @investment.errors.any? %>
  <div id="errors">
    <h4>Error:</h4>

    <ul>
    <% @investment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    <br>
  </div>
    <% end %>

<%=form_for([user, investment]) do |f|%>

  <%=f.hidden_field :user_id, :value => @user.id %>

  <%=f.label :quantity, "Quantity:" %>
  <%=f.number_field :quantity %><br>
  <br>
  <%=f.label :price, "Price:" %>
  <%=f.text_field :price %><br>

  <p>Select From Existing Funds or Add a New Fund:</p>

  Choose Fund: <%= f.collection_select :fund_id, Fund.all, :id, :symbol, include_blank: true %><br><br>

  <%= f.fields_for :new_fund do |fund_fields| %>
    <%= fund_fields.label :symbol, "Fund Symbol:" %>
    <%= fund_fields.text_field :symbol %><br>
  <% end %><br>

  <%=f.submit %><br>
<%end%>
<br><br>

app/views/investments/index.html.erb
<h1>Explore All Investments:</h1>

<table style="width:100%">
  <tr>
    <th align="left">Fund:</th>
    <th align="left">Quantity:</th>
    <th align="left">Price:</th>
    <th align="left">Created By:</th>
    <th align="left">Date Created:</th>
  </tr>
  <% @investments.order(created_at: :desc).each do |investment| %>
    <tr>
      <td><%= investment.fund.symbol%></td>
      <td><%= investment.quantity%></td>
      <td><%= investment.price%></td>
      <td><%= investment.user.username %></td>
      <td><%= investment.created_at.strftime("%m/%d/%Y") %></td>
        <tr>
    <% end %>
</table>

<br>

app/views/investments/latest.html.erb
<div class="center-horizontal block">
<h1>Most Recent Investments:</h1>
<table style="width:100%">
  <tr>
    <th align="left">Fund:</th>
    <th align="left">Quantity:</th>
    <th align="left">Price:</th>
    <th align="left">Created By:</th>
    <th align="left">Date Created:</th>
  </tr>
  <% @latest_investments.each do |investment| %>
    <tr>
      <td><%= investment.fund.symbol%></td>
      <td><%= investment.quantity%></td>
      <td><%= investment.price%></td>
      <td><%= investment.user.username %></td>
      <td><%= investment.created_at.strftime("%m/%d/%Y") %></td>
        <tr>
    <% end %>
</table>
<br>

</div>

app/views/investments/new.html.erb
<div class="center-horizontal block">
  <h1>New Investment:</h1>
  <div>
    <%=render partial: 'form', locals: {user: @user, investment: @investment}%>
  </div>
</div>

app/views/investments/newest.html.erb
<div class="center-horizontal block">
<h1>Newest Investments:</h1>

<table style="width:100%">
  <tr>
    <th align="left">Fund:</th>
    <th align="left">Quantity:</th>
    <th align="left">Price:</th>
    <th align="left">Created By:</th>
    <th align="left">Date Created:</th>
  </tr>
  <% @newest_investments.each do |investment| %>
    <tr>
      <td><%= investment.fund.symbol%></td>
      <td><%= investment.quantity%></td>
      <td><%= investment.price%></td>
      <td><%= investment.user.username %></td>
      <td><%= investment.created_at.strftime("%m/%d/%Y") %></td>
        <tr>
    <% end %>
</table>
<br>

</div>

app/views/investments/show.html.erb
<h1>Investment:</h1>
<h4>Quantity:<%= investment.fund.symbol %></h4>
<h4>Quantity:<%= investment.quantity %></h4>
<h4>Price:<%= investment.price %></h4><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>I.nvest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

  <footer>
    <br>
    <% if sign_in? %>
      <div id="navbar">
        <%= button_to "My Investments", user_path(current_user), method: :get, class: 'float-button' %>
        <%= button_to "New Investment", new_user_investment_path(current_user), method: :get, class: 'float-button' %>
        <%= button_to "Latest Investments", latest_path, method: :get, class: 'float-button' %>
        <%= button_to "See All Funds", user_funds_path(current_user), method: :get, class: 'float-button' %>
        <%= button_to "Top Funds", top_funds_path, method: :get, class: 'float-button' %>
        <%= button_to "All Users", users_path, method: :get, class: 'float-button' %>
        <%= button_to "My Account", edit_user_path(current_user), method: :get, class: 'float-button' %>
        <%= button_to "Sign Out", signout_path, method: :get, class: 'float-button' %>
      </div>
    <%end%>
  </footer>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="errors">
    <h4>Error:</h4>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    <br>
  </div>
<% end %>

<%= form_for @user do |f|%>
  <%= f.label :email, "Email: " %><br>
  <%= f.email_field :email, class: 'field-size' %><br>
  <br>
  <%= f.label :name, "Name: " %><br>
  <%= f.text_field :name, class: 'field-size' %><br>
  <br>
  <%= f.label :username, "Username: " %><br>
  <%= f.text_field :username, class: 'field-size' %><br>
  <br>
  <%= f.label :password, "Password: "%><br>
  <%= f.password_field :password, class: 'field-size' %><br>
  <br>
  <%= submit_tag "Submit", class: 'button' %>
<%end%>
<br><br>

app/views/users/edit.html.erb
<div id="errors">
  <h4><%= flash[:notice] %></h4>
</div>

<div class="center-horizontal block">
  <h1>Update Info For <%=@user.name%></h1>
  <%=render partial: 'form', locals: {user: @user}%>
</div>

app/views/users/index.html.erb
<div class="center-horizontal block">
  <h1>View User Profiles</h1>

  <br>
  <table>
    <tr>
      <th>User</th>
      <th>Investments</th>
      <th>Funds</th>
      <th>Profile</th>
    </tr>
    <% @users.order(created_at: :desc).each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.investments.count %></td>
        <td><%= user.funds.count %></td>
        <td><%= button_to "View", user_path(user), method: :get %>
    <tr>
      <% end %>
  </table>

  <br><br>
</div>

app/views/users/new.html.erb
<div class="center-horizontal">
  <h1>Sign Up:</h1>
  <%=render partial: 'form', locals: {user: @user}%>
</div>

app/views/users/show.html.erb
<div class="center-horizontal block">
  <% if @user == current_user %>
    <h1>Hello <%= @user.name %>!</h1>
  <% else %>
    <h1><%= @user.name %></h1>
  <% end %>

  <h3>Investments</h3>
    <table style="width:100%">
      <tr>
        <th align="left">Fund:</th>
        <th align="left">Quantity:</th>
        <th align="left">Price:</th>
        <th align="left">Date Created:</th>
        <% if @user == current_user %>
          <th align="left">Remove?</th>
        <% end %>
      </tr>
    <% @user.investments.order(created_at: :desc).each do |investment| %>
      <tr>
        <td><%= investment.fund.symbol%></td>
        <td><%= investment.quantity%></td>
        <td><%= investment.price%></td>
        <td><%= investment.created_at.strftime("%m/%d/%Y") %></td>
        <% if @user == current_user %>
          <td><%= button_to "Delete", user_investment_path(current_user, investment), method: :delete, data: {confirm: "You sure?"} %>
        <% end %>
      </tr>
      <% end %>
    </table>
    <br><br>

<h3>Funds</h3>
  <ul>
    <% @user.funds.uniq.each do |fund| %>
    <li><%= fund.symbol %></li>
    <% end %>
  </ul>
<br><br>
</div>